include:
  # ðŸ”¹ ì¢Œì¸¡(Left) ë¹Œë“œ - ìŠ¬ë ˆì´ë¸Œ
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem-dongle-left

  # ðŸ”¹ ìš°ì¸¡(Right) ë¹Œë“œ - ìŠ¬ë ˆì´ë¸Œ
  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem-dongle-right

  # ðŸ”¹ ì¢Œì¸¡ BLE ë¹Œë“œ (Studio ì—°ê²°ìš©)
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
    artifact-name: totem-ble-left

  # ðŸ”¹ ìš°ì¸¡ BLE ë¹Œë“œ
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem-ble-right

  # ðŸ”¹ ë™ê¸€ + YADS í™”ë©´ ë²„ì „ (USB + Screen)
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    cmake-args: >
      -DCONFIG_PM=n
      -DCONFIG_PM_DEVICE=n
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=0
      -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: totem-dongle-yads

  # ðŸ”¹ ë™ê¸€ ê¸°ë³¸ ë²„ì „ (USB)
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    cmake-args: >
      -DCONFIG_PM=n
      -DCONFIG_PM_DEVICE=n
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=0
    snippet: zmk-usb-logging
    artifact-name: totem-dongle

  # ðŸ”¹ ì„¤ì • ì´ˆê¸°í™”ìš© ë¹Œë“œ
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: totem-settings-reset
