manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0.3.0 # or main if newer than 0.3.0
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: Dexter-KBD
      revision: main
  self:
    path: config
