manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 641514a97db345f499dd50b0360e594270f008fe
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: dexterkbd
      revision: faeb747b3ad77a3fa9f38da216d2d1cf3d953295
  self:
    path: config
