manifest:
  remotes:
  - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
    - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: dexterkbd
      revision: main
  self:
    path: config
