manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 641514a97db345f499dd50b0360e594270f008fe
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: dexterkbd
      revision: 0314e266ea4e4fca9c54181a638d04f37bfc5636
  self:
    path: config
