manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dexterkbd
      url-base: https://github.com/Dexter-KBD
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 641514a97db345f499dd50b0360e594270f008fe
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: dexterkbd
      revision: 43b88909fdf5c54aad69779128d5532cf12d3127
  self:
    path: config
